name: Publish Crates

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  crate_publish:
    environment: "publish to crates.io"
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          echo "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-11 main" | sudo tee -a /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get install -y clang-11 cmake
      - name: Symlink libclang.so
        run: sudo ln -s /lib/x86_64-linux-gnu/libclang-11.so.1 /lib/x86_64-linux-gnu/libclang.so
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
      - run: |
          export crate_name=$(python3 -c "print('$GITHUB_REF'.split('/')[2].rsplit('_v', 1)[0])")
          echo "Publishing crate: $crate_name"
          cargo publish --locked --token ${CARGO_REGISTRY_TOKEN} --package "$crate_name" --dry-run
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          RUSTFLAGS: "-A ambiguous_glob_reexports"
          RUST_BACKTRACE: "1"
