name: Publish Crates

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  crate_publish:
    environment: "publish to crates.io"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
      - run: |
          crate_name=$(python3 -c "print('$GITHUB_REF'.split('/')[2].rsplit('_v', 1)[0])") && \
          cargo publish --token ${CARGO_REGISTRY_TOKEN} --package "$crate_name" --dry-run
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
